# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import order_pb2 as order__pb2


class OrderStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetState = channel.unary_unary(
        '/orders.Order/GetState',
        request_serializer=order__pb2.GetRequest.SerializeToString,
        response_deserializer=order__pb2.GetReply.FromString,
        )
    self.SetState = channel.unary_unary(
        '/orders.Order/SetState',
        request_serializer=order__pb2.SetRequest.SerializeToString,
        response_deserializer=order__pb2.SetReply.FromString,
        )


class OrderServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OrderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetState': grpc.unary_unary_rpc_method_handler(
          servicer.GetState,
          request_deserializer=order__pb2.GetRequest.FromString,
          response_serializer=order__pb2.GetReply.SerializeToString,
      ),
      'SetState': grpc.unary_unary_rpc_method_handler(
          servicer.SetState,
          request_deserializer=order__pb2.SetRequest.FromString,
          response_serializer=order__pb2.SetReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'orders.Order', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
